services:
  - type: web
    name: nayepankh-volunteer-portal
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn volunteer_portal.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.10.11"