# Generated by Django 5.2.15 on 2026-06-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('skill', models.CharField(choices=[('Teaching', 'Teaching'), ('Medical', 'Medical'), ('Technology', 'Technology'), ('Marketing', 'Marketing'), ('Design', 'Design'), ('Legal', 'Legal'), ('Finance', 'Finance'), ('Other', 'Other')], max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-joined_date'],
            },
        ),
    ]
